In [3]:
import spacy

In [4]:
from spacy.lang.en.stop_words import STOP_WORDS
len(STOP_WORDS)

326

In [6]:
nlp=spacy.load('en_core_web_sm')
doc=nlp("we just opened our wings, the flying part is coming soon")
for token in doc:
  if token.is_stop:
    print(token)

we
just
our
the
part
is

In [7]:
def preprocess(test):
  doc=nlp(test)
  no_stop_words=[token.text for token in doc if not token.is_stop and not token.is_punct]
  return no_stop_words

In [8]:
preprocess("Musk Wants time to prepare for a trial over his")

['Musk', 'Wants', 'time', 'prepare', 'trial']

In [13]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df=pd.read_json("combined.json", lines=True)
df.shape

Saving combined.json to combined.json

(13087, 6)

In [14]:
df.head()

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13087 entries, 0 to 13086
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          12810 non-null  object
 1   title       13087 non-null  object
 2   contents    13087 non-null  object
 3   date        13087 non-null  object
 4   topics      13087 non-null  object
 5   components  13087 non-null  object
dtypes: object(6)
memory usage: 613.6+ KB

In [16]:
df.describe()

,id,title,contents,date,topics,components
count,12810,13087,13087,13087,13087,13087
unique,12672,12887,13080,2400,253,810
top,13-526,Northern California Real Estate Investor Agree...,"Miami residents Raymond Arias, 42, and his w...",2018-04-13T00:00:00-04:00,[],[Criminal Division]
freq,3,8,2,20,8399,2680

In [18]:
df=df[df["topics"].str.len()!=0]
df.head(5)

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division]
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]"

In [20]:
df.shape

(4688, 6)

In [21]:
df=df.head(100)
df.shape

(100, 6)

In [22]:
df["contents"]

4      The U.S. Department of Justice, the U.S. Envir...
7      A 131-count criminal indictment was unsealed t...
19     The United States Attorney’s Office for the Mi...
22     21st Century Oncology LLC, has agreed to pay $...
23     21st Century Oncology Inc. and certain of its ...
                             ...
316    Doctor Hid Millions in Secret Accounts in Pana...
318    Defendant Concealed Bank Accounts in Panama an...
321    An Alaskan couple was charged in federal court...
322    A husband and wife pleaded guilty yesterday to...
324    A resident of Big Lake, Alaska was indicted on...
Name: contents, Length: 100, dtype: object

In [23]:
len(df["contents"].iloc[4])

5504

In [26]:
df["contents_new"]=df["contents"].apply(preprocess)

In [27]:
df.head(5)

,id,title,contents,date,topics,components,contents_new
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division],"[U.S., Department, Justice, U.S., Environmenta..."
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division],"[131, count, criminal, indictment, unsealed, t..."
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U...","[United, States, Attorney, Office, Middle, Dis..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division],"[21st, Century, Oncology, LLC, agreed, pay, $,..."
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]","[21st, Century, Oncology, Inc., certain, subsi..."

In [28]:
df["contents"].iloc[4][:300]

'21st Century Oncology Inc. and certain of its subsidiaries and affiliates have agreed to pay $26 million to the government to resolve a self-disclosure relating to the submission of false attestations regarding the company’s use of electronic health records software and separate allegations that the'

In [29]:
df["contents_new"].iloc[4][:300]

['21st',
 'Century',
 'Oncology',
 'Inc.',
 'certain',
 'subsidiaries',
 'affiliates',
 'agreed',
 'pay',
 '$',
 '26',
 'million',
 'government',
 'resolve',
 'self',
 'disclosure',
 'relating',
 'submission',
 'false',
 'attestations',
 'company',
 'use',
 'electronic',
 'health',
 'records',
 'software',
 'separate',
 'allegations',
 'violated',
 'False',
 'Claims',
 'Act',
 'submitting',
 'causing',
 'submission',
 'claims',
 'certain',
 'services',
 'provided',
 'pursuant',
 'referrals',
 'physicians',
 'improper',
 'financial',
 'relationships',
 '\xa0 ',
 'Justice',
 'Department',
 'committed',
 'zealously',
 'investigating',
 'improper',
 'financial',
 'relationships',
 'potential',
 'compromise',
 'physicians',
 'medical',
 'judgment',
 'said',
 'Acting',
 'Assistant',
 'Attorney',
 'General',
 'Chad',
 'A.',
 'Readler',
 'Justice',
 'Department',
 'Civil',
 'Division',
 '\xa0 ',
 'work',
 'companies',
 'accept',
 'responsibility',
 'past',
 'compliance',
 'failures',
 'promptly',
 'corrective',
 'action',
 ' \xa0 ',
 '21st',
 'Century',
 'Oncology',
 'headquartered',
 'Fort',
 'Myers',
 'Florida',
 'owns',
 'operates',
 'subsidiaries',
 'affiliates',
 'United',
 'States',
 'provide',
 'integrated',
 'cancer',
 'care',
 '\xa0 ',
 'business',
 '21st',
 'Century',
 'Oncology',
 'subsidiaries',
 'affiliates',
 'employ',
 'physicians',
 'specialty',
 'fields',
 'radiation',
 'oncology',
 'medical',
 'oncology',
 'urology',
 '\xa0  \xa0 ',
 'settlement',
 'announced',
 'today',
 'resolves',
 'conduct',
 'self',
 'disclosed',
 'company',
 'payments',
 'government',
 'Medicare',
 'Electronic',
 'Health',
 'Records',
 'EHR',
 'Incentive',
 'Program',
 '\xa0 ',
 'Medicare',
 'EHR',
 'Incentive',
 'Program',
 'physicians',
 'attest',
 'meaningful',
 'use',
 'certified',
 'EHR',
 'technology',
 'receive',
 'incentive',
 'payments',
 'avoid',
 'downward',
 'adjustments',
 'certain',
 'Medicare',
 'claims',
 '\xa0 ',
 'self',
 'disclosure',
 '21st',
 'Century',
 'Oncology',
 'reported',
 'knowingly',
 'submitted',
 'caused',
 'submission',
 'false',
 'attestations',
 'CMS',
 'concerning',
 'employed',
 'physicians',
 'use',
 'EHR',
 'software',
 '\xa0 ',
 'company',
 'reported',
 'support',
 'attestations',
 'employees',
 'falsified',
 'data',
 'company',
 'use',
 'EHR',
 'software',
 'fabricated',
 'software',
 'utilization',
 'reports',
 'superimposed',
 'EHR',
 'vendor',
 'logos',
 'reports',
 'look',
 'legitimate',
 '\xa0  \xa0 ',
 'settlement',
 'represents',
 'office',
 'continued',
 'commitment',
 'ensuring',
 'compliance',
 'important',
 'federal',
 'health',
 'care',
 'laws',
 'said',
 'Acting',
 'U.S.',
 'Attorney',
 'Stephen',
 'Muldrow',
 'Middle',
 'District',
 'Florida',
 '\xa0 ',
 'appreciate',
 '21st',
 'Century',
 'Oncology',
 'self',
 'reported',
 'major',
 'fraud',
 'affecting',
 'Medicare',
 'pleased',
 'company',
 'agreed',
 'accept',
 'financial',
 'responsibility',
 'past',
 'compliance',
 'failures',
 '\xa0 ',
 'settlement',
 'resolves',
 'government',
 'allegations',
 'violations',
 'physician',
 'self',
 'referral',
 'law',
 'commonly',
 'referred',
 'Stark',
 'Law',
 '\xa0 ',
 'Stark',
 'Law',
 'prohibits',
 'entity',
 'submitting',
 'claims',
 'Medicare',
 'designated',
 'health',
 'services',
 'performed',
 'pursuant',
 'referrals',
 'physicians',
 'entity',
 'financial',
 'relationship',
 'certain',
 'designated',
 'exceptions',
 'apply',
 '\xa0 ',
 'government',
 'alleged',
 '21st',
 'Century',
 'Oncology',
 'certain',
 'subsidiaries',
 'affiliates',
 'violated',
 'FCA',
 'submitting',
 'causing',
 'submission',
 'claims',
 'services',
 'performed',
 'pursuant',
 'referrals',
 'physicians',
 'compensation',
 'satisfy',
 'exception',
 'Stark']